### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by DimonYoing** [creeperplayer20/C20s-JoinUI#1]
Can you please do so that I can change instead of the text "send" to another text

**Comment by creeperplayer20** [comment]
Like when you press the submit button a command will be executed?

**Comment by creeperplayer20** [comment]
Btw you can change the content of that UI to anything in the plugin_data > JoinUI > config.yml

**Comment by DimonYoing** [comment]
I have to enter that when you write /rules there is a "send" button there, I would like to change it, but I don't know how

**Comment by DimonYoing** [comment]
After clicking the button, the user interface will close

**Comment by DimonYoing** [comment]
And also can you add 2 more buttons with a section?

**Comment by DimonYoing** [comment]
for example, I write /rules there I want to click chat rules, then this section opens , and there will be rules

**Comment by DimonYoing** [comment]
And in the second button there will be another section

**Comment by DimonYoing** [comment]
That is, first the text and then 2 buttons leading to the information section

**Comment by DimonYoing** [comment]
And so that the "send" button could change the text itself to another text

**Comment by creeperplayer20** [comment]
Sure, add me on discord: creeperplayer20

**Comment by DimonYoing** [comment]
sent a request
